"""initial business state schema

Revision ID: 1ff960285b68
Revises:
Create Date: 2026-08-10 00:18:18.109402
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "1ff960285b68"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "captures",
        sa.Column("capture_id", sa.String(length=64), nullable=False),
        sa.Column("source_id", sa.String(length=512), nullable=False),
        sa.Column("file_sha256", sa.String(length=64), nullable=False),
        sa.Column("parse_status", sa.String(length=32), nullable=False),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("capture_id"),
        sa.UniqueConstraint("file_sha256"),
    )
    op.create_table(
        "security_incidents",
        sa.Column("incident_id", sa.String(length=64), nullable=False),
        sa.Column("tenant_ref", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("automation_state", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("incident_id"),
    )
    op.create_index(
        op.f("ix_security_incidents_status"), "security_incidents", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_security_incidents_tenant_ref"), "security_incidents", ["tenant_ref"], unique=False
    )
    op.create_table(
        "action_recommendations",
        sa.Column("recommendation_id", sa.String(length=64), nullable=False),
        sa.Column("recommendation_type", sa.String(length=64), nullable=False),
        sa.Column("incident_id", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"], ["security_incidents.incident_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("recommendation_id"),
    )
    op.create_index(
        op.f("ix_action_recommendations_incident_id"),
        "action_recommendations",
        ["incident_id"],
        unique=False,
    )
    op.create_table(
        "agent_tasks",
        sa.Column("task_id", sa.String(length=64), nullable=False),
        sa.Column("task_type", sa.String(length=24), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("assigned_agent_type", sa.String(length=64), nullable=False),
        sa.Column("incident_id", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"], ["security_incidents.incident_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("task_id"),
    )
    op.create_index(
        op.f("ix_agent_tasks_incident_id"), "agent_tasks", ["incident_id"], unique=False
    )
    op.create_table(
        "associations",
        sa.Column("association_id", sa.String(length=64), nullable=False),
        sa.Column("association_type", sa.String(length=32), nullable=False),
        sa.Column("association_basis", sa.String(length=32), nullable=False),
        sa.Column("incident_id", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"], ["security_incidents.incident_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("association_id"),
    )
    op.create_index(
        op.f("ix_associations_incident_id"), "associations", ["incident_id"], unique=False
    )
    op.create_table(
        "audit_records",
        sa.Column("audit_id", sa.String(length=64), nullable=False),
        sa.Column("incident_id", sa.String(length=64), nullable=True),
        sa.Column("chain_key", sa.String(length=64), nullable=False),
        sa.Column("sequence_no", sa.Integer(), nullable=False),
        sa.Column("actor_type", sa.String(length=16), nullable=False),
        sa.Column("actor_id", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("object_type", sa.String(length=64), nullable=False),
        sa.Column("object_id", sa.String(length=255), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("payload_redacted", sa.JSON(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("prev_hash", sa.String(length=64), nullable=True),
        sa.Column("record_hash", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"], ["security_incidents.incident_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("audit_id"),
        sa.UniqueConstraint("chain_key", "sequence_no", name="uq_audit_chain_sequence"),
        sa.UniqueConstraint("record_hash"),
    )
    op.create_index(
        "ix_audit_chain_order", "audit_records", ["chain_key", "sequence_no"], unique=False
    )
    op.create_index(
        op.f("ix_audit_records_incident_id"), "audit_records", ["incident_id"], unique=False
    )
    op.create_table(
        "confirmed_facts",
        sa.Column("fact_id", sa.String(length=64), nullable=False),
        sa.Column("fact_type", sa.String(length=64), nullable=False),
        sa.Column("incident_id", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"], ["security_incidents.incident_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("fact_id"),
    )
    op.create_index(
        op.f("ix_confirmed_facts_incident_id"), "confirmed_facts", ["incident_id"], unique=False
    )
    op.create_table(
        "evidence_references",
        sa.Column("evidence_id", sa.String(length=64), nullable=False),
        sa.Column("incident_id", sa.String(length=64), nullable=True),
        sa.Column("source_type", sa.String(length=16), nullable=False),
        sa.Column("source_record_id", sa.String(length=255), nullable=False),
        sa.Column("evidence_type", sa.String(length=32), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("sensitivity", sa.String(length=16), nullable=False),
        sa.Column("allowed_agent_types", sa.JSON(), nullable=False),
        sa.Column("supersedes_evidence_id", sa.String(length=64), nullable=True),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"], ["security_incidents.incident_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_evidence_id"], ["evidence_references.evidence_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("evidence_id"),
        sa.UniqueConstraint(
            "source_type", "source_record_id", "content_sha256", name="uq_evidence_source_content"
        ),
    )
    op.create_index(
        op.f("ix_evidence_references_incident_id"),
        "evidence_references",
        ["incident_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evidence_references_source_type"),
        "evidence_references",
        ["source_type"],
        unique=False,
    )
    op.create_table(
        "network_flows",
        sa.Column("flow_id", sa.String(length=64), nullable=False),
        sa.Column("capture_id", sa.String(length=64), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["capture_id"], ["captures.capture_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("flow_id"),
    )
    op.create_table(
        "raw_events",
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("capture_id", sa.String(length=64), nullable=True),
        sa.Column("source_type", sa.String(length=16), nullable=False),
        sa.Column("event_kind", sa.String(length=32), nullable=False),
        sa.Column("source_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["capture_id"], ["captures.capture_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_table(
        "risk_assessments",
        sa.Column("assessment_id", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("incident_id", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"], ["security_incidents.incident_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("assessment_id"),
    )
    op.create_index(
        op.f("ix_risk_assessments_incident_id"), "risk_assessments", ["incident_id"], unique=False
    )
    op.create_table(
        "security_signals",
        sa.Column("signal_id", sa.String(length=64), nullable=False),
        sa.Column("signal_type", sa.String(length=48), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("incident_id", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"], ["security_incidents.incident_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("signal_id"),
    )
    op.create_index(
        op.f("ix_security_signals_incident_id"), "security_signals", ["incident_id"], unique=False
    )
    op.create_table(
        "action_requests",
        sa.Column("action_request_id", sa.String(length=64), nullable=False),
        sa.Column("recommendation_id", sa.String(length=64), nullable=False),
        sa.Column("action_type", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("incident_id", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"], ["security_incidents.incident_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["recommendation_id"], ["action_recommendations.recommendation_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("action_request_id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(
        op.f("ix_action_requests_incident_id"), "action_requests", ["incident_id"], unique=False
    )
    op.create_table(
        "agent_findings",
        sa.Column("finding_id", sa.String(length=64), nullable=False),
        sa.Column("task_id", sa.String(length=64), nullable=False),
        sa.Column("finding_type", sa.String(length=64), nullable=False),
        sa.Column("incident_id", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"], ["security_incidents.incident_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["task_id"], ["agent_tasks.task_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("finding_id"),
    )
    op.create_index(
        op.f("ix_agent_findings_incident_id"), "agent_findings", ["incident_id"], unique=False
    )
    op.create_index(op.f("ix_agent_findings_task_id"), "agent_findings", ["task_id"], unique=False)
    op.create_table(
        "agent_results",
        sa.Column("result_id", sa.String(length=64), nullable=False),
        sa.Column("task_id", sa.String(length=64), nullable=False),
        sa.Column("task_status", sa.String(length=24), nullable=False),
        sa.Column("incident_id", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"], ["security_incidents.incident_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["task_id"], ["agent_tasks.task_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("result_id"),
    )
    op.create_index(
        op.f("ix_agent_results_incident_id"), "agent_results", ["incident_id"], unique=False
    )
    op.create_index(op.f("ix_agent_results_task_id"), "agent_results", ["task_id"], unique=False)
    op.create_table(
        "dns_events",
        sa.Column("dns_event_id", sa.String(length=64), nullable=False),
        sa.Column("flow_id", sa.String(length=64), nullable=False),
        sa.Column("capture_id", sa.String(length=64), nullable=False),
        sa.Column("source_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["capture_id"], ["captures.capture_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["flow_id"], ["network_flows.flow_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("dns_event_id"),
    )
    op.create_table(
        "http_events",
        sa.Column("http_event_id", sa.String(length=64), nullable=False),
        sa.Column("flow_id", sa.String(length=64), nullable=False),
        sa.Column("capture_id", sa.String(length=64), nullable=False),
        sa.Column("source_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["capture_id"], ["captures.capture_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["flow_id"], ["network_flows.flow_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("http_event_id"),
    )
    op.create_table(
        "approval_records",
        sa.Column("approval_id", sa.String(length=64), nullable=False),
        sa.Column("action_request_id", sa.String(length=64), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("request_digest", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["action_request_id"], ["action_requests.action_request_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("approval_id"),
    )
    op.create_index(
        op.f("ix_approval_records_action_request_id"),
        "approval_records",
        ["action_request_id"],
        unique=False,
    )
    op.create_table(
        "execution_results",
        sa.Column("execution_id", sa.String(length=64), nullable=False),
        sa.Column("action_request_id", sa.String(length=64), nullable=False),
        sa.Column("overall_status", sa.String(length=24), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["action_request_id"], ["action_requests.action_request_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("execution_id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(
        op.f("ix_execution_results_action_request_id"),
        "execution_results",
        ["action_request_id"],
        unique=False,
    )
    op.create_table(
        "policy_decisions",
        sa.Column("policy_decision_id", sa.String(length=64), nullable=False),
        sa.Column("action_request_id", sa.String(length=64), nullable=False),
        sa.Column("decision", sa.String(length=32), nullable=False),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["action_request_id"], ["action_requests.action_request_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("policy_decision_id"),
        sa.UniqueConstraint("action_request_id"),
    )
    op.create_table(
        "verification_results",
        sa.Column("verification_id", sa.String(length=64), nullable=False),
        sa.Column("execution_id", sa.String(length=64), nullable=False),
        sa.Column("overall_status", sa.String(length=24), nullable=False),
        sa.Column("incident_id", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["execution_id"], ["execution_results.execution_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"], ["security_incidents.incident_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("verification_id"),
    )
    op.create_index(
        op.f("ix_verification_results_execution_id"),
        "verification_results",
        ["execution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_verification_results_incident_id"),
        "verification_results",
        ["incident_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_verification_results_incident_id"), table_name="verification_results")
    op.drop_index(op.f("ix_verification_results_execution_id"), table_name="verification_results")
    op.drop_table("verification_results")
    op.drop_table("policy_decisions")
    op.drop_index(op.f("ix_execution_results_action_request_id"), table_name="execution_results")
    op.drop_table("execution_results")
    op.drop_index(op.f("ix_approval_records_action_request_id"), table_name="approval_records")
    op.drop_table("approval_records")
    op.drop_table("http_events")
    op.drop_table("dns_events")
    op.drop_index(op.f("ix_agent_results_task_id"), table_name="agent_results")
    op.drop_index(op.f("ix_agent_results_incident_id"), table_name="agent_results")
    op.drop_table("agent_results")
    op.drop_index(op.f("ix_agent_findings_task_id"), table_name="agent_findings")
    op.drop_index(op.f("ix_agent_findings_incident_id"), table_name="agent_findings")
    op.drop_table("agent_findings")
    op.drop_index(op.f("ix_action_requests_incident_id"), table_name="action_requests")
    op.drop_table("action_requests")
    op.drop_index(op.f("ix_security_signals_incident_id"), table_name="security_signals")
    op.drop_table("security_signals")
    op.drop_index(op.f("ix_risk_assessments_incident_id"), table_name="risk_assessments")
    op.drop_table("risk_assessments")
    op.drop_table("raw_events")
    op.drop_table("network_flows")
    op.drop_index(op.f("ix_evidence_references_source_type"), table_name="evidence_references")
    op.drop_index(op.f("ix_evidence_references_incident_id"), table_name="evidence_references")
    op.drop_table("evidence_references")
    op.drop_index(op.f("ix_confirmed_facts_incident_id"), table_name="confirmed_facts")
    op.drop_table("confirmed_facts")
    op.drop_index(op.f("ix_audit_records_incident_id"), table_name="audit_records")
    op.drop_index("ix_audit_chain_order", table_name="audit_records")
    op.drop_table("audit_records")
    op.drop_index(op.f("ix_associations_incident_id"), table_name="associations")
    op.drop_table("associations")
    op.drop_index(op.f("ix_agent_tasks_incident_id"), table_name="agent_tasks")
    op.drop_table("agent_tasks")
    op.drop_index(
        op.f("ix_action_recommendations_incident_id"), table_name="action_recommendations"
    )
    op.drop_table("action_recommendations")
    op.drop_index(op.f("ix_security_incidents_tenant_ref"), table_name="security_incidents")
    op.drop_index(op.f("ix_security_incidents_status"), table_name="security_incidents")
    op.drop_table("security_incidents")
    op.drop_table("captures")
    # ### end Alembic commands ###
